### PR TITLE
Add support for ROS noetic 

### PR DESCRIPTION
**Pull request by jpbusch**
- modified `CMakeLists.txt` and `package.xml` to enable parallel ROS and ROS 2 build of `udp_msgs`

@flynneva, could you please review and then release for ROS noetic? Let me know if any further changes are required.

### CODE REVIEW

**Comment by jpbusch** [comment]
Hi @flynneva, I would appreciate getting feedback from you.

**Comment by flynneva** [comment]
@jpbusch sorry for just seeing this now. I'll take a look tomorrow and get back to you!

**Comment by flynneva** [comment]
@jpbusch I'd be fine with these changes, but do you think you could also add an action to the CI pipeline for Noetic then too? If not, no biggie I can add one in another PR since I need to update the ROS 2 ones anyways

**Comment by jpbusch** [comment]
@flynneva, thanks for reviewing! I have extended the CI to include ROS noetic.
Unfortunately it was not possible to extend the current matrix strategy in `ros_ci.yml`, so I had to add another job. The `action-ros-ci` needs a different parameter for ROS 1 (`target-ros1-distro`).

**Comment by flynneva** [comment]
@jpbusch perfect. Once the CI passes I'll merge it and do a release, thanks again for the contribution 🙏🏼

**Comment by jpbusch** [comment]
Great, thank you, @flynneva!

**Comment by flynneva** [comment]
@jpbusch ill see about cutting a new release tomorrow if I can find the time 👍 thanks for the contributions!

**Pull request merged**
